MSISDN, examples, patterns
vippsas/vipps-login-api pull request #29
Opened 2020-09-24 15:39 UTC by cloveras

2020-09-25 06:49 UTC, Jo-Inge commented on docs/swagger.json
> +            "example": "´47912345678'",
```suggestion
            "example": "47912345678",
```

2020-09-25 06:50 UTC, Jo-Inge commented on docs/swagger.json
> +            "example": "7d78a726-af92-499e-b857-de263ef9a969"
Burde også legges til UserinfoApiV2

2020-09-25 06:50 UTC, Jo-Inge commented on docs/swagger.json
> +            "example": "c06c4afe-d9e1-4c5d-939a-177d752a0944"
Burde også legges til UserinfoApiV2

2020-09-25 06:50 UTC, Jo-Inge commented on docs/swagger.json
> +            "example": "31.12.2000"
Burde også legges til UserinfoApiV2

2020-09-25 06:53 UTC, Jo-Inge commented on docs/swagger.json
> +            "description": "End-User's telephone number on MSISDN format, up to 15 digits.",
Burde også legges til UserinfoApiV2

2020-09-25 08:51 UTC, Jo-Inge requested changes
Bra at det blir lagt på eksempel på responsen. Det var et par plasser der det kun var lagt til i den ene responsen.

2020-10-15 07:53 UTC, Oyvinkg approved these changes

2020-10-15 08:35 UTC, merged